### ISSUE TITLE
Task 3: Script

### ISSUE THREAD

**Issue by admarga** [ubsuny/GroverPhysics#4]
For the YouTube video, include both a specific outline for material to cover in the _3 to 5 minute video_ and also a final script of what was said in the video. The script can be written before or after production of the video, but it likely should be done beforehand to make a smooth video.

The outline should clearly illustrate all key points to be covered in the video. This includes topics such as:

- A brief history of Grover's algorithm
- Why use Grover's algorithm
- What does Grover's algorithm do
- Real life example(s) that use Grover's algorithm
- Implementation in Qiskit of the algorithm

The outline can be in any format; a simple .txt file could do if it is clear enough, but a well-structured PDF of how the video should progress is preferred.

**Comment by lmeiler** [comment]
Austin uploaded script. Issue closed.
