### ISSUE TITLE
Task 2: Markdown, unit test, and visualizations

### ISSUE THREAD

**Issue by admarga** [ubsuny/GroverPhysics#5]
In addition to the required linting and docstrings, include some clean markdown that makes the Jupyter Notebook readable. For any circuits, use `circuit.draw()` at key points to demonstrate the circuit.

Try to actively use other forms of visualization in the notebook.

Unit test sections of code if possible.

**Comment by lmeiler** [comment]
We've done the Markdown in the notebook, and the visualizations in the notebook and presentation. No unit tests were applied.
